### ISSUE TITLE
Bug in NodeHelper code

### ISSUE THREAD

**Issue by unlimitedsola** [ForestryMC/MagicBees#1]
https://github.com/ForestryMC/MagicBees/blob/mc-1.7.10/src/main/java/magicbees/main/utils/compat/thaumcraft/NodeHelper.java#L108-L113
`20 < rollAttempts` always be false
for real?

**Comment by mezz** [comment]
Actually?

**Comment by mezz** [comment]
I guess I can nerf it and fix the code, but there's no Thaumcraft to test against on 1.10 so this bug will have to remain open for a bit.

Please try to make better reports, this is in the top 100 for bad reporting style.

**Comment by MysteriousAges** [comment]
@SolaKun In the time it took you to file this report, you could've opened a PR to fix that.

But yeah, I guess being snarky about things motivates people to do things faster. 👏👏
