### ISSUE TITLE
commit 3ca629d Serverside crash and problems

### ISSUE THREAD

**Issue by darkmtbg2** [ForestryMC/MagicBees#16]
Server side of the mod does not work in a dedicated server environment. or if single player gets opened to LAN then when you attempt to leave the game Minecraft just locks up needing you to kill Minecraft or wait for extremely long time(haven't checked how long)

In dedicated server none of the botanical flowers will work crashing the server logs for the crash
https://pastebin.com/We2V9ap6
https://pastebin.com/DfKqiqwa

**Comment by Elec332** [comment]
Im calling EntityItem#getAge(), which is a client side only method for some weird reason, Ill look into another way to get that value.

**Comment by Elec332** [comment]
Fixed in latest commit
