### ISSUE TITLE
Batty Bee Resets Apiary

### ISSUE THREAD

**Issue by lparkjordan** [ForestryMC/MagicBees#21]
Minecraft 1.11.12, Forge 13.20.0.2315. Running version 0.72a of All The Mods 2. I bred a batty queen (using Gendustry) and placed it in an industrial apiary. After a few moments, the apiary seemed to reset itself - the bee, all the apiary upgrades, and all the RF in the apiary disappeared, leaving behind an empty apiary. 

I bred another batty queen and tried a regular apiary instead, and had a similar result - after a few moments, the bee disappeared. I've tried this in both multiplayer and singleplayer - the result is the same.

**Comment by Elec332** [comment]
Any logs?

**Comment by lparkjordan** [comment]
Here's a [relevant-looking crash report](https://pastebin.com/PkuWsetz). Let me know if you want the whole thing.

**Comment by lparkjordan** [comment]
Tried putting it in an alveary this evening. This time, the game actually crashed entirely. Here's the resulting crash report: 
[crash-2017-07-13_22.24.52-server.txt](https://github.com/ForestryMC/MagicBees/files/1147433/crash-2017-07-13_22.24.52-server.txt)

**Comment by rmunn** [comment]
Immediate cause of this bug looks like `java.lang.NoClassDefFoundError: elec332/core/util/EntityHelper`. @Elec332, looks like your EntityHelper class wasn't loaded in this person's installation. Which .jar file is it supposed to live in?

**Comment by Elec332** [comment]
ElecCore, thats the weird thing...

**Comment by lparkjordan** [comment]
If it helps, my installation seems to have ElecCore version 1.7.425.
