### ISSUE TITLE
[1.7.10] Valiant bees cannot drop from hives (and a couple related bugs)

### ISSUE THREAD

**Issue by rmunn** [ForestryMC/MagicBees#23]
## First bug: Valiant bees cannot drop

There's a bug in the 1.7.10 branch that makes it impossible for Valiant bees to drop from any of the world-placed hives they're supposed to drop from. I'll demonstrate the problem, then propose a solution.

First, let's look at the [code that sets up the hive drop rates](https://github.com/ForestryMC/MagicBees/blob/mc-1.7.10/src/main/java/magicbees/block/types/HiveType.java#L54) ([permalink](https://github.com/ForestryMC/MagicBees/blob/155d6386475150755006a0b13379c61468fd0af9/src/main/java/magicbees/block/types/HiveType.java#L54)). The regular drops have a drop rate of 80%, then there's a 15% chance of getting a rain-tolerant version of that hive's regular drop, and then a 5% chance of a Valiant bee (which will, if it drops, be guaranteed to be rain-tolerant). E.g.,

```java
CURIOUS.drops.add(new HiveDrop(BeeSpecies.MYSTICAL.getGenome(), combs, 80).setIgnoblePercentage(0.7f));
CURIOUS.drops.add(new HiveDrop(BeeGenomeManager.addRainResist(BeeSpecies.MYSTICAL.getGenome()), combs, 15));
CURIOUS.drops.add(valiantDrop);
```

Now let's look at the [code that figures out the actual drops](https://github.com/ForestryMC/MagicBees/blob/mc-1.7.10/src/main/java/magicbees/block/types/HiveType.java#L125) ([permalink](https://github.com/ForestryMC/MagicBees/blob/155d6386475150755006a0b13379c61468fd0af9/src/main/java/magicbees/block/types/HiveType.java#L125)). It picks a random number between 1 and 100, then goes through all the possible drops and checks if that random number is less than or equal to the drop chance. Once it succeeds at finding the first drop, it will stop looking at the other possible drops. It repeats this cycle for princess and drones, so there's a maximum of 1 princess and 1 drone available from each hive:

```java
dart = world.rand.nextInt(100);
for (IHiveDrop drop : drops)
{
    if (dart <= drop.getChance(world, x, y, z))
    {
        hiveDrops.add(drop.getPrincess(world, x, y, z, fortune));
        break;
    }
}

dart = world.rand.nextInt(100);
for (IHiveDrop drop : drops)
{
    if (dart <= drop.getChance(world, x, y, z))
    {
        hiveDrops.add(drop.getDrones(world, x, y, z, fortune));
        break;
    }
}
```

However, notice that the random number is assigned **outside** the for loop. So every time the bee drops are checked, it's using the same random number. So any chosen number that would possibly be able to generate a Valiant bee (e.g., a number between 0 and 5) will *also* be able to generate the normal drop for that hive -- and once the normal drop is chosen, the Valiant bee will *not* be chosen because the loop exits as soon as one drop has been generated.

To actually have a chance to generate the Valiant bee, the `rand.nextInt()` call needs to be *inside* the loop:

```java
for (IHiveDrop drop : drops)
{
    dart = world.rand.nextInt(100);
    if (dart <= drop.getChance(world, x, y, z))
    {
        hiveDrops.add(drop.getPrincess(world, x, y, z, fortune));
        break;
    }
}
```

And the same for drones.

Furthermore, there are a couple of other minor bugs in this code. I'll put them in their own headings.

## Second bug: off-by-one error in probability checks

The 80% chance of getting a regular hive bee is actually 81%, and the 5% chance of getting a Valiant bee would be 6% if it could ever happen. That's because the Java `rand.nextInt(100)` call doesn't generate a number between 1 and 100, it generates a number between 0 and 99. So testing for `<= 5` will succeed for six numbers: 0, 1, 2, 3, 4, and 5. If a 5% chance is desired instead of 6%, or an 80% chance instead of 81%, the test should actually be `< drop.getChance()` instead of `<= drop.getChance()`.

## Third bug (maybe): Valiant bee is far less likely than 5%

This may be a bug, or it may be intended behavior, but I think it's probably a bug, or at least unintended behavior. Once the first bug is fixed by moving the random-number generation inside the `for` loop, so the Valiant bee actually has a non-zero chance to drop, its chances still won't actually be 5%. (Or 6% if the second bug is not yet fixed). That's because before rolling for the Valiant bee, first you have to *not* generate a hive bee or a rain-tolerant version of itself. Let's say the first and second bugs get fixed (the random-number generation moved inside the loop, and the `<=` check is changed to `<` so the chance of the hive bees truly is the 80% it appears to be). Then the actual chance of generating a Valiant bee is:

20% chance of NOT getting a hive bee
\* 85% chance of NOT getting a rain-tolerant hive bee
\* 5% chance of getting a Valiant bee
= .2 \* .85 \* .05 = .0085

So the chances of getting a Valiant bee from any given hive are actually 0.85%.

If this is considered a bug, and the desired chance for Valiant bees is actually to have them drop from 5% of all Magic Bees hives, the simplest way to achieve that result is to flip the order in which drop chances are added to the list. Instead of adding them from most likely to least likely, add them from least likely to most likely. I.e.,

```java
CURIOUS.drops.add(valiantDrop);
CURIOUS.drops.add(new HiveDrop(BeeGenomeManager.addRainResist(BeeSpecies.MYSTICAL.getGenome()), combs, 15));
CURIOUS.drops.add(new HiveDrop(BeeSpecies.MYSTICAL.getGenome(), combs, 80).setIgnoblePercentage(0.7f));
```

Now the chances of getting a Valient bee from any given hive are exactly 5%. The chance of getting a rain-tolerant hive bee is 95% \* 15% = 14.25% (because if you get a Valiant bee, the code stops checking for further drops). And the chance of getting a normal hive bee is 95% \* 85% \* 80% = 64.6%.

Also, the chance of getting *nothing at all* from a hive would not change: whether the drops are checked in most-likely to least-likely order, or in least-likely to most-likely order, the chance of getting *nothing at all* from a hive would be either 20% \* 85% \* 95% or 95% \* 85% \* 20%. EIther way, that's a 16.15% chance of getting nothing at all from any given hive, which means an 83.85% chance of getting *something*. But by putting the Valiant bee in front rather than behind, you'll make it far more likely that those drops will include a Valiant bee:

If checking in most-likely to least-likely order:

Chance of normal bee = 80%
Chance of rain-tolerant bee = 20% \* 15% = 3%
Chance of Valiant bee = 20% \* 85% \* 5% = 0.85%
Total chance of any bee = .8 + .03 + .0085 = .8385 = 83.85%

If checking in least-likely to most-likely order:

Chance of Valiant bee = 5%
Chance of rain-tolerant bee = 95% \* 15% = 14.25%
Chance of normal bee = 95% \* 85% \* 80% = 64.6%
Total chance of any bee = .05 + .1425 + .646 = .8385 = 83.85%

## Summary

I've reported three related bugs in one issue, because all three are in a single file of the code and can all be fixed at once with a single PR, so I figured it would be easier to track them all as a single issue. I'd be happy to create that PR, but I won't be able to create it until about 12 hours from now. So if you want to fix these bugs first before I get to, I won't object. If you do, though, please leave a comment in this issue to let me know so that I don't duplicate your work. :-) Also, if you'd prefer for me to split these three bugs into three separate issues, I can do that too.

Finally, there's a **maintainer decision needed** on bug 3. Do you want the actual chance of Valiant bees to be 5%, or to be 0.85%? The way the code is structured now, their actual chances (if bugs 1 and 2 were eliminated) would be 0.85% — but maybe that's intended. If you tell me "Don't fix bug 3 because it's not a bug)" then I'll leave that part of the code as-is when I create my PR. But if you tell me, "Yes, the chance of Valiant drops was supposed to be truly 5%", then I'll change the order of the drops so that Valiant comes first.

**Comment by rmunn** [comment]
P.S. I've been looking at the `1.10/1.11-rewrite` branch to see if the bug is present in that branch as well, but I haven't yet found the part of the code that *actually generates* the drops, so I can't tell if the bug is there as well. In the Extra Bees code, the 1.10 branch has the random-number generation inside the loop the way it should be, but I haven't yet been able to tell where the hive-drop code is for Magic Bees. So I'm afraid you'll have to verify whether this bug is in the `1.10/1.11-rewrite` branch yourself, since I was unable to find the right part of the code.

**Comment by rmunn** [comment]
Looks like I won't be able to verify whether this bug exists on the `1.10/1.11-rewrite` branch, because the code that manages the hive drops is apparently somewhere in the `elec332.core.compat.forestry.bee.HiveDrop` class, which I don't have access to. So I'll have to leave it up to @Elec332 to double-check that branch, and see if the Valiant bee has a chance to show up or not.

But the 1.7.10 code definitely does need fixing so that Valiant bees can show up.

**Comment by rmunn** [comment]
After looking into the corresponding code in Forestry and Extra Bees, it looks like [the collection of possible hive drops is shuffled](https://github.com/ForestryMC/Binnie/blob/3ff4957a10c4d5eee5da8c21265b408f7ae29e10/src/main/java/binnie/extrabees/blocks/BlockExtraBeeHive.java#L111) before checking the random chances. So the best thing is to fix Magic Bees to also shuffle the collection, so that its behavior is the same as that of Forestry and Extra Bees. The random chances should still be moved inside the `for` loop, but there's no need to re-order the registration of Valiant bee drops if the collection gets shuffled.

**Comment by Elec332** [comment]
The code for drop selection for 1.10/1.11 is here:
https://github.com/Elecs-Mods/ElecCore/blob/master/src/main/java/elec332/core/compat/forestry/bee/IHiveEnum.java#L61

**Comment by rmunn** [comment]
Then there's no need for further action, because the key parts of this bugfix (shuffle the collection before selecting from it, and pick random numbers inside the `for` loop) are already in the drop selection code for 1.10/1.11. So it's now been fixed on all active branches.
