### ISSUE TITLE
Bugfix release for 1.7.10?

### ISSUE THREAD

**Issue by rmunn** [ForestryMC/MagicBees#29]
Last week (July 22) there were [new releases uploaded to CurseForge](https://minecraft.curseforge.com/projects/magic-bees?gameCategorySlug=mc-mods&projectID=65764) for 1.10 and 1.11, that included several bugfixes like the fix to drop rates that I submitted earlier.

However, I don't see a bugfix release for 1.7.10 yet. Is the intent to just leave 1.7.10 as-is, and never release new versions for it even if they only contain fixes to known bugs? Or was a 1.7.10 bugfix release simply missed by oversight (because main development has moved to the 1.10+ versions), and you do intend to keep releasing bugfix versions for 1.7.10?

**Comment by Elec332** [comment]
Ill release a bugfix for 1.7.10 soon, but im not going to actively work on 1.7.10
