### ISSUE TITLE
Magic bees do not show up when added to FTB Beyond pack mc 1.10.2

### ISSUE THREAD

**Issue by AlexFin** [ForestryMC/MagicBees#30]
As the title states, the bees from the pack do not show up in nei/jei in FTB beyond. Other items such as the varius honeycomb show up, but the bees themselves do not.

**Comment by AlexFin** [comment]
With further investigation I have found that they are in the game, but they do not show up in NEI/JEI

**Comment by Kris1432** [comment]
what are you looking up? The specific bee names?

**Comment by AlexFin** [comment]
Yes, or just using @magicbees to see what items it shows from the modpack

**Comment by Kris1432** [comment]
@magicbees will not show the bees, as they're registered with Forestry, not Magic Bees itself.

**Comment by AlexFin** [comment]
Looking for @ forestry also does not show the bees

**Comment by AlexFin** [comment]
But I think I might have another problem I packed that's causing this to
happen along with other issues. For example, the porcine bees effect causes
my game to crash

**Comment by Elec332** [comment]
![screenshot_5](https://user-images.githubusercontent.com/6115944/29560302-e3fbd080-8731-11e7-8357-282cad2e401f.png)
If you only see these bees, then there's nothing wrong, the rest of the bees have a "secret bee type" flag, meaning they won't show up in JEI/NEI or the creative tab
