### ISSUE TITLE
[suggestion] change naming convention of jar

### ISSUE THREAD

**Issue by Zygus42** [ForestryMC/MagicBees#35]
It would help mod pack developers a lot to have your mod with the "forestry-" prefix so that all forestry related mods sorted together in the mods folder.  ie:
        forestry-MagicBees-1.12-3.1.5.jar
instead of
        MagicBees-1.12-3.1.5.jar

**Comment by Elec332** [comment]
No, this is not going to happen. The mod is called MagicBees, not forestry-magicbees, if pack devs want to name the file differently, they can, but the filename convention on curse will not change.
