### ISSUE TITLE
[1.12.2] Integration

### ISSUE THREAD

**Issue by 016Nojr** [ForestryMC/MagicBees#39]
Any plans on adding back support for previous supported mods, in 1.12.2? 

Thinking about Botania, Thermal Expansion and Applied Energistics

**Comment by Elec332** [comment]
These are already in MB
https://github.com/ForestryMC/MagicBees/blob/1.12/src/main/java/magicbees/bees/EnumBeeSpecies.java#L1450-L2076

**Comment by 016Nojr** [comment]
oh, they are supported. I will change it a bit then. When I search "Fluix" in JEI, I do see a Genetic Template (Gendustry) with the Fluix species, however there are no Fluix Princess/Queen/Drone shown.
Same case with Thermal Expansion bees


Is it caused by not having the configs in the config file? (My config only got Botania stuff in it)
