### ISSUE TITLE
[1.12.2] Crash with new Forestry update

### ISSUE THREAD

**Issue by Diamondman121314** [ForestryMC/MagicBees#41]
The new Forestry update(s) seemed to have broke MagicBees, unfortunately.

https://pastebin.com/zhASDf4t

**Comment by xAlicatt** [comment]
https://gist.github.com/xAlicatt/6f871d8896b93ac89d39f70efac535d7

Same

**Comment by Diamondman121314** [comment]
If you know how to compile from GitHub, you'll be able to get the fixed version. I'm not sure if there is a Jenkins page for this, I couldn't find one.

**Comment by 3TUSK** [comment]
@Diamondman121314 http://jenkins.ic2.player.to/job/Forestry_1.11/

**Comment by SDUBZ** [comment]
[crash-2017-11-05_22.11.39-client.txt](https://github.com/ForestryMC/MagicBees/files/1443953/crash-2017-11-05_22.11.39-client.txt)

also getting this crash
any news when the fix will be pushed to curseforge etc? @Nedelosk

**Comment by Nedelosk** [comment]
I don't have the permissions to push it to curseforge. @Elec332 or @mezz has to do that for me.

**Comment by mezz** [comment]
I have pushed a new build today.
