### ISSUE TITLE
[Suggestion] Don't load bees if the required mod isn't loaded

### ISSUE THREAD

**Issue by PokeMaserJ** [ForestryMC/MagicBees#45]
Example: If I don't have AE2 in my instance, don't load the Skystone bee. Even though there is no recipe for it. it still shows under JEI Bees for produce and it probably shows in the Escritoire.

**Comment by Elec332** [comment]
This would mean that, when AE 2 is removed, you would lose all associated bees. This way, if it gets re-added later, it's still there

**Comment by PokeMaserJ** [comment]
What if I never have AE2 or some other mod that has bees that can produce resources? Could you just not load those bees? mezz said "it's not hard to fix" when I asked in the Foresty discord, " would it be hard for Magic Bees / Binnie's to not load bees that are for various mod items"

**Comment by Elec332** [comment]
Short answer: I _can_ indeed just not register the bees in the mod is unavailable. Not sure _if_ in going to do it.
Ill make up my mind upcoming weekend.
