### ISSUE TITLE
Using the Acceleration upgrade in Gendustry Apiary crashes server

### ISSUE THREAD

**Issue by dmodoomsirius** [ForestryMC/MagicBees#47]
https://gist.github.com/dmodoomsirius/a5a34b6ba009c2152288b4bb54bd26cd
using a normal Forestry Apiary does not crash the server. Also reporting this to bdew on the gendustry issue tracker.
Effect is from Career bees.
https://github.com/bdew/gendustry/issues/243

**Comment by Drakefyre27** [comment]
For the record, a normal career bee (temporal queen), with the same effect works just fine when using gendustry.
Same with using standart (no acceleration effect) magic bee with gendustry.

**Comment by bdew** [comment]
Hm is there something i can do about this on my side?

From the crash it looks like effectData is null, but that is managed by forestry itself and i don't think i can do anything about that?

@mezz any idea?

**Comment by bdew** [comment]
Also i've compared AlleleEffectThrottled between magic bees and forestry and it looks like MB version is missing this part that would ensure the data is valid i think: https://github.com/ForestryMC/ForestryMC/blob/mc-1.12/src/main/java/forestry/apiculture/genetics/alleles/AlleleEffectThrottled.java#L36-L42

**Comment by Elec332** [comment]
![image](https://user-images.githubusercontent.com/6115944/33796756-50619bdc-dcfb-11e7-88fc-27421374ff6b.png)

Nope, it's present

**Comment by Elec332** [comment]
I think/hope the fix for #40 also fixed this. Please open a new issue if it didn't.
