### ISSUE TITLE
Missing Hives

### ISSUE THREAD

**Issue by Alan19** [ForestryMC/MagicBees#48]
The oblivion, deep, and infernal hives are not in 1.12, making attuned, oblivion, and infernal bees unobtainable.

**Comment by uehlbran** [comment]
I can confirm this is happening. However, infernal hives do spawn. You cannot obtain Oblivion, draconic, nameless, and abandoned bees however.

MC version: 1.12.2
Magic Bees version: 3.1.7

**Comment by Alan19** [comment]
You can obtain ethereal by using the hiveacynth to get attuned bees @uehlbran

**Comment by uehlbran** [comment]
I don't need attuned bees though. I can already get those. I need abandoned bees, oblivion, and nameless.

I can get ethereal already.

**Comment by Elec332** [comment]
I found both hives ingame:
http://prntscr.com/hw3ubh
http://prntscr.com/hw4203
