### ISSUE TITLE
Rockin' bee crashes game

### ISSUE THREAD

**Issue by ghost** [ForestryMC/MagicBees#53]
Putting the Rockin' bee into an apiary of any kind causes the game to crash, I persume when it's trying to spawn a Basalz as it's effect. Any way to get around this? Using the Direwolf20 1.12 pack

EDIT: Seeing as the file didn't upload, here's the pastebin of it: https://pastebin.com/8sXXXZW5

**Comment by temp1011** [comment]
I found this crash log for the same problem http://paste.feed-the-beast.com/view/0b4fd28c
  EDIT: https://github.com/ForestryMC/MagicBees/issues/40 looks similar but is closed.

**Comment by Elec332** [comment]
Fixed in upcoming version
