### ISSUE TITLE
[1.12.2] Game crashes when a bee collector's jar is generated through a recurrent complex script block

### ISSUE THREAD

**Issue by Alan19** [ForestryMC/MagicBees#57]
When generating a structure with a bee collector's jar through Recurrent Complex, the game crashes and becomes impossible to rejoin. This was caused by a jar with common drones with modified traits (it has aggressive). 
This also occurred with a older version of the structure with oblivion, infernal and attuned drones with modified traits, generated through a script block that would generate the jars as a separate structure.

Crash log: https://pastebin.com/2Lu3ttYb
Structure file: https://github.com/belathus/Wanderlust-Renewed/blob/master/structures/active/HostileAlveary.rcst

**Comment by NotActuallyTerry** [comment]
Hi,

We received this crash when one of our server members placed an imperial drone in a bee collector's jar. We do not have Recurrent Complex within the pack at all.

https://gist.github.com/twrist/0794eaae64bd4662c249abe64af70d30
