### ISSUE TITLE
Rockin and Gelin not dropping Thermal Dynamics items

### ISSUE THREAD

**Issue by DigitalSketch** [ForestryMC/MagicBees#58]
I've run the Gelid and Rockin bees through multiple lifespans with no genetic modifications, and I can't get the Gelid to drop Cryotheum dust, and I can't get the Rockin to drop Petrotheum dust.  JEI is telling me that there is a 9% chance for drops.  The Pyro and Amped bees are dropping the secondary thermal item though.

I'm using the 1.12.2-3.1.9 version of Magic Bees.

**Comment by Elec332** [comment]
Bees only produce their speciality if they are jubilant, which by default means they must be in a biome with the exact temerature & humidity the bees prefer, not just within the range of accepted values.
