### ISSUE TITLE
Crash with ThermalExpansion

### ISSUE THREAD

**Issue by Skillotic0703** [ForestryMC/MagicBees#6]
https://pastebin.com/8sFcFSVf

**Comment by DeadSix27** [comment]
Same here, https://gist.github.com/DeadSix27/5d065ec4d9ca68ffe2b5ed2304de68e8

Checked if there is a way to disable the thermal expansion int. until its fixed, but the config does not even generate before it crashes.

**Comment by Emerald-Chicken** [comment]
Yep, here as well. https://pastebin.com/mreEf2C4

**Comment by Mikahil2012** [comment]
I took this crash too: https://paste.ee/p/S6Sjv#tNG5trMl8gmJWPTyPeEy11uk0iEp6KWs

**Comment by xAlicatt** [comment]
@DeadSix27 Even when you load up a profile with just forestry and magic bees installed, it is able to load successfully, but no config file is generated. Well...there's a file...it's just empty.

**Comment by Boomflex** [comment]
Yeah same here: https://pastebin.com/LpKp81WH

**Comment by MrSapient** [comment]
Same 🗡

**Comment by Elec332** [comment]
Please update to ElecCore 1.7.425
