### ISSUE TITLE
Scornful Oblivion Uncraftable - 1.12.2 

### ISSUE THREAD

**Issue by Keaton1188** [ForestryMC/MagicBees#60]
Hey, the Essence of Scornful Oblivion is not craftable, all items match what it needs and it doesn't pop up.
Tested this on a server and SP, same outcome. 

MagicBees Version: MagicBees-1.12.2-3.1.9.jar

FTB Pack: Revelations

MCVersion: 1.12.2

SpongeVersion: 1.12.2-2555-7.1.0-BETA-2840

**Comment by Jobs2k** [comment]
In case it is needed in any way, I'm confirming the issue for Revelations (at least):
![oblivion](https://user-images.githubusercontent.com/29983487/38964569-58c3462e-436f-11e8-8f58-544d41e7d504.JPG)

No result available in any crafting inventory.

**Comment by Corosauce** [comment]
Same here with revelations pack.

**Comment by Elec332** [comment]
It requires a dragon egg in the middle, which will not be consumed

**Comment by Darkere** [comment]
The dragon egg does not appear in the JEI recipe. With the dragon egg the recipe works but consumes the dragon egg.
