### ISSUE TITLE
[Request] Config to disable worldgen

### ISSUE THREAD

**Issue by Saereth** [ForestryMC/MagicBees#62]
Particularly the decorative blocks that spawn around certain hives like glowstone/redstone. It would be very nice if we could disable the extra blocks. For those making packs with very closely defined oregen they can mess with pack progression pretty badly and no way to deal with them currently other than removing the mod.

**Comment by DWX12** [comment]
I'm looking for this exact addition to the config file. I would like to use the mod, but the lack of control over it is messing with the progression I'm trying to set up for the pack I'm working on.

I would like to see options for hives for what biome(s) they can spawn in and to be able to disable them if need be. The main option I would like to see is the ability to disable the blocks they generate.

Thank you and hope that these options will be available in the next update.
