### ISSUE TITLE
[1.12.2] Magnet does not work properly.

### ISSUE THREAD

**Issue by ProsperCraft** [ForestryMC/MagicBees#63]
MagicBees-1.12.2-3.1.9

Even with the highest tier magnet, it isn't picking up items properly.

![2018-03-13_16 54 52](https://user-images.githubusercontent.com/4427684/37676961-12f8e064-2c3f-11e8-97b6-014d721588d2.png)

![2018-03-13_16 54 54](https://user-images.githubusercontent.com/4427684/37676974-1f49ef34-2c3f-11e8-84bb-99c65b790bda.png)

![2018-03-13_16 55 31](https://user-images.githubusercontent.com/4427684/37676976-21b7f28e-2c3f-11e8-8fd0-953cb14f89dd.png)

These were on a server.

**Comment by ProsperCraft** [comment]
Video below -
https://gyazo.com/92c4bc7232eebbd2b8e16092a616efda

This was shot in single player.

**Comment by retep998** [comment]
Would it be possible to have a new version published with this change? I'd like to be able to use the Mysterious Magnet. Thanks.
