### ISSUE TITLE
MagicBees crashing in 1.12.2

### ISSUE THREAD

**Issue by Lilithvia** [ForestryMC/MagicBees#66]
---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 5/3/18 3:25 PM
Description: Initializing game

java.lang.RuntimeException: Error creating model for Bee Collector's Jar
	at magicbees.client.ModelHandler.loadSpecialModels(ModelHandler.java:257)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_327_ModelHandler_loadSpecialModels_ModelBakeEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.client.ForgeHooksClient.onModelBake(ForgeHooksClient.java:386)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:30)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at magicbees.client.ModelHandler.loadSpecialModels(ModelHandler.java:257)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_327_ModelHandler_loadSpecialModels_ModelBakeEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.client.ForgeHooksClient.onModelBake(ForgeHooksClient.java:386)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:30)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 8 (amd64) version 6.2
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1140925984 bytes (1088 MB) / 1744830464 bytes (1664 MB) up to 3221225472 bytes (3072 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.3.2655 42 mods loaded, 42 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                  | Version               | Source                                           | Signature                                |
	|:----- |:------------------- |:--------------------- |:------------------------------------------------ |:---------------------------------------- |
	| UCH   | minecraft           | 1.12.2                | minecraft.jar                                    | None                                     |
	| UCH   | mcp                 | 9.42                  | minecraft.jar                                    | None                                     |
	| UCH   | FML                 | 8.0.99.99             | forge-1.12.2-14.23.3.2655.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge               | 14.23.3.2655          | forge-1.12.2-14.23.3.2655.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | bdlib               | 1.14.3.12             | bdlib-1.14.3.12-mc1.12.2.jar                     | None                                     |
	| UCH   | bibliocraft         | 2.4.3                 | BiblioCraft[v2.4.3][MC1.12.0].jar                | None                                     |
	| UCH   | jei                 | 4.8.5.159             | jei_1.12.2-4.8.5.159.jar                         | None                                     |
	| UCH   | forestry            | 5.8.0.263             | forestry_1.12.2-5.8.0.263.jar                    | None                                     |
	| UCH   | binniecore          | 2.5.0.164             | binnie-mods-1.12.2-2.5.0.164.jar                 | None                                     |
	| UCH   | binniedesign        | 2.5.0.164             | binnie-mods-1.12.2-2.5.0.164.jar                 | None                                     |
	| UCH   | genetics            | 2.5.0.164             | binnie-mods-1.12.2-2.5.0.164.jar                 | None                                     |
	| UCH   | botany              | 2.5.0.164             | binnie-mods-1.12.2-2.5.0.164.jar                 | None                                     |
	| UCH   | extrabees           | 2.5.0.164             | binnie-mods-1.12.2-2.5.0.164.jar                 | None                                     |
	| UCH   | extratrees          | 2.5.0.164             | binnie-mods-1.12.2-2.5.0.164.jar                 | None                                     |
	| UCH   | codechickenlib      | 3.1.6.339             | CodeChickenLib-1.12.2-3.1.6.339-universal.jar    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | redstoneflux        | 2.0.1                 | RedstoneFlux-1.12-2.0.1.2-universal.jar          | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UCH   | brandonscore        | 2.4.0                 | BrandonsCore-1.12-2.4.0.152-universal.jar        | None                                     |
	| UCH   | buildcraftlib       | 7.99.16               | buildcraft-7.99.16.jar                           | None                                     |
	| UCH   | buildcraftcore      | 7.99.16               | buildcraft-7.99.16.jar                           | None                                     |
	| UCH   | buildcraftbuilders  | 7.99.16               | buildcraft-7.99.16.jar                           | None                                     |
	| UCH   | buildcraftenergy    | 7.99.16               | buildcraft-7.99.16.jar                           | None                                     |
	| UCH   | buildcraftfactory   | 7.99.16               | buildcraft-7.99.16.jar                           | None                                     |
	| UCH   | buildcraftrobotics  | 7.99.16               | buildcraft-7.99.16.jar                           | None                                     |
	| UCH   | buildcrafttransport | 7.99.16               | buildcraft-7.99.16.jar                           | None                                     |
	| UCH   | buildcraftsilicon   | 7.99.16               | buildcraft-7.99.16.jar                           | None                                     |
	| UCH   | chameleon           | 1.12-4.1.3            | Chameleon-1.12-4.1.3.jar                         | None                                     |
	| UCH   | chickenchunks       | 2.4.1.71              | ChickenChunks-1.12.2-2.4.1.71-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | chisel              | MC1.12.2-0.2.0.31     | Chisel-MC1.12.2-0.2.0.31.jar                     | None                                     |
	| UCH   | cofhcore            | 4.3.11                | CoFHCore-1.12.2-4.3.11.6-universal.jar           | None                                     |
	| UCH   | cofhworld           | 1.1.1                 | CoFHWorld-1.12.2-1.1.1.12-universal.jar          | None                                     |
	| UCH   | cyclopscore         | 0.11.5                | CyclopsCore-1.12.2-0.11.5.jar                    | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| UCH   | commoncapabilities  | 1.4.0                 | CommonCapabilities-1.12-1.4.0.jar                | None                                     |
	| UCH   | draconicevolution   | 2.3.10                | Draconic-Evolution-1.12-2.3.10.284-universal.jar | None                                     |
	| UCH   | jeibees             | 0.9.0.5               | jeibees-0.9.0.5-mc1.12.2.jar                     | None                                     |
	| UCH   | journeymap          | 1.12.2-5.5.2          | journeymap-1.12.2-5.5.2.jar                      | None                                     |
	| UCH   | magicbees           | 1.0                   | MagicBees-1.12.2-3.1.9.jar                       | None                                     |
	| UCH   | mantle              | 1.12-1.3.1.21         | Mantle-1.12-1.3.1.21.jar                         | None                                     |
	| UCH   | millenaire          | MillÃ©naire 6.2.1-ip.3 | millenaire-6.2.1-ip.3.jar                        | None                                     |
	| UCH   | harvestcraft        | 1.12.2t               | Pam_s HarvestCraft 1.12.2t.jar                   | None                                     |
	| UCH   | redstonearsenal     | 2.3.11                | RedstoneArsenal-1.12.2-2.3.11.5-universal.jar    | None                                     |
	| UCH   | tconstruct          | 1.12.2-2.9.1.65       | TConstruct-1.12.2-2.9.1.65.jar                   | None                                     |
	| UCH   | twilightforest      | 3.6.345               | twilightforest-1.12.2-3.6.345-universal.jar      | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.2.11762 Compatibility Profile Context' Renderer: 'AMD Radeon HD 7310 Graphics'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)

	List of loaded APIs: 
		* BuildCraftAPI|blocks (1.0) from buildcraft-7.99.16.jar
		* BuildCraftAPI|boards (2.0) from buildcraft-7.99.16.jar
		* BuildCraftAPI|core (2.2) from buildcraft-7.99.16.jar
		* BuildCraftAPI|crops (1.1) from buildcraft-7.99.16.jar
		* BuildCraftAPI|enums (1.0) from buildcraft-7.99.16.jar
		* BuildCraftAPI|events (2.0) from buildcraft-7.99.16.jar
		* BuildCraftAPI|facades (1.1) from buildcraft-7.99.16.jar
		* BuildCraftAPI|filler (5.0) from buildcraft-7.99.16.jar
		* BuildCraftAPI|fuels (2.0) from buildcraft-7.99.16.jar
		* BuildCraftAPI|gates (4.1) from buildcraft-7.99.16.jar
		* BuildCraftAPI|items (1.1) from buildcraft-7.99.16.jar
		* BuildCraftAPI|library (2.0) from buildcraft-7.99.16.jar
		* BuildCraftAPI|lists (1.0) from buildcraft-7.99.16.jar
		* BuildCraftAPI|power (1.3) from buildcraft-7.99.16.jar
		* BuildCraftAPI|recipes (3.0) from buildcraft-7.99.16.jar
		* BuildCraftAPI|robotics (3.0) from buildcraft-7.99.16.jar
		* BuildCraftAPI|statements (1.1) from buildcraft-7.99.16.jar
		* BuildCraftAPI|tiles (1.2) from buildcraft-7.99.16.jar
		* BuildCraftAPI|tools (1.0) from buildcraft-7.99.16.jar
		* BuildCraftAPI|transport (5.0) from buildcraft-7.99.16.jar
		* Chisel-API (0.0.1) from Chisel-MC1.12.2-0.2.0.31.jar
		* ChiselAPI|Carving (0.0.1) from Chisel-MC1.12.2-0.2.0.31.jar
		* cofhapi (2.2.0) from CoFHCore-1.12.2-4.3.11.6-universal.jar
		* cofhapi|block (2.2.0) from CoFHCore-1.12.2-4.3.11.6-universal.jar
		* cofhapi|core (2.2.0) from CoFHCore-1.12.2-4.3.11.6-universal.jar
		* cofhapi|item (2.2.0) from CoFHCore-1.12.2-4.3.11.6-universal.jar
		* cofhapi|tileentity (2.2.0) from CoFHCore-1.12.2-4.3.11.6-universal.jar
		* cofhapi|util (2.2.0) from CoFHCore-1.12.2-4.3.11.6-universal.jar
		* commoncapabilities|api (0.0.1) from CommonCapabilities-1.12-1.4.0.jar
		* DraconicEvolution|API (1.3) from Draconic-Evolution-1.12-2.3.10.284-universal.jar
		* ForestryAPI|apiculture (5.0.0) from forestry_1.12.2-5.8.0.263.jar
		* ForestryAPI|arboriculture (4.3.0) from forestry_1.12.2-5.8.0.263.jar
		* ForestryAPI|book (5.8.1) from forestry_1.12.2-5.8.0.263.jar
		* ForestryAPI|circuits (3.1.0) from forestry_1.12.2-5.8.0.263.jar
		* ForestryAPI|climate (5.0.0) from forestry_1.12.2-5.8.0.263.jar
		* ForestryAPI|core (5.7.0) from forestry_1.12.2-5.8.0.263.jar
		* ForestryAPI|farming (5.8.0) from forestry_1.12.2-5.8.0.263.jar
		* ForestryAPI|food (1.1.0) from forestry_1.12.2-5.8.0.263.jar
		* ForestryAPI|fuels (3.0.0) from forestry_1.12.2-5.8.0.263.jar
		* ForestryAPI|genetics (5.7.0) from forestry_1.12.2-5.8.0.263.jar
		* ForestryAPI|greenhouse (5.2.0) from forestry_1.12.2-5.8.0.263.jar
		* ForestryAPI|gui (5.8.0) from forestry_1.12.2-5.8.0.263.jar
		* ForestryAPI|hives (4.1.0) from forestry_1.12.2-5.8.0.263.jar
		* ForestryAPI|lepidopterology (1.4.0) from forestry_1.12.2-5.8.0.263.jar
		* ForestryAPI|mail (3.1.0) from forestry_1.12.2-5.8.0.263.jar
		* ForestryAPI|modules (5.7.0) from forestry_1.12.2-5.8.0.263.jar
		* ForestryAPI|multiblock (3.0.0) from forestry_1.12.2-5.8.0.263.jar
		* ForestryAPI|recipes (5.4.0) from forestry_1.12.2-5.8.0.263.jar
		* ForestryAPI|storage (5.0.0) from forestry_1.12.2-5.8.0.263.jar
		* ForestryAPI|world (2.1.0) from forestry_1.12.2-5.8.0.263.jar
		* journeymap|client-api (1.4) from journeymap-1.12.2-5.5.2.jar
		* journeymap|client-api-display (1.4) from journeymap-1.12.2-5.5.2.jar
		* journeymap|client-api-event (1.4) from journeymap-1.12.2-5.5.2.jar
		* journeymap|client-api-model (1.4) from journeymap-1.12.2-5.5.2.jar
		* journeymap|client-api-util (1.4) from journeymap-1.12.2-5.5.2.jar
		* JustEnoughItemsAPI (4.13.0) from jei_1.12.2-4.8.5.159.jar
	Launched Version: 1.12.2-forge1.12.2-14.23.3.2655
	LWJGL: 2.9.4
	OpenGL: AMD Radeon HD 7310 Graphics GL version 4.2.11762 Compatibility Profile Context, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 2x AMD E1-1200 APU with Radeon(tm) HD Graphics

**Comment by Elec332** [comment]
Do you have any steps to reproduce? I cannot reproduce this issue...

**Comment by Lilithvia** [comment]
Yeah, let me find my install again

**Comment by Elec332** [comment]
Please use the _latest_ Forestry when testing

**Comment by Lilithvia** [comment]
So apparently it's actually a conflict with Tabula, so I'm no longer surprised there's a conflict.

**Comment by Elec332** [comment]
If this ever happens again (even though I do not get _why_ and _how_ this can happen), make sure you have "oldJarModel" set to false in the config as a workaround.
