### ISSUE TITLE
No Recipe for Silicon Bee

### ISSUE THREAD

**Issue by jeddell** [ForestryMC/MagicBees#69]
Working through all of the Magic bees in MC Revelation Modpack 2.0. There is no recipe for  the silicon bee. Nor can I find any information on this bee in any of t he forums.

**Comment by NimonoSolenze** [comment]
Can confirm in a custom modpack made by a friend- None of Silicon, Certus, nor Fluix Bee have a breeding recipe- nor a produce excepting the default Honey Comb. Looking at the code, it appears all 3 are listed as having a produce of their namesake OreResource, yet JEI Bees says nothing. As for their breeding... I suspect it may have to do with this:

public void registerMutations() {
            registerMutation(AE_SKYSTONE.isActive() ? AE_SKYSTONE : EARTHY, IRON, 17);
}

Excerpt from mutation for Silicon bee. Note how it doesn't match the format of calling the bee species seen on Skystone Bees, which ARE working:

public void registerMutations() {
            registerMutation(EARTHY, WINDY, 20).requireResource(BeeIntegrationInterface.aeSkyStone);
}

I suspect it's that .isActive() ? stuff that's blocking these three bees from being bred, as their formatting is the same as the first example

**Comment by Draskh** [comment]
I have the same issue.

![2018-09-22_18 03 18](https://user-images.githubusercontent.com/26455012/46207576-2ca63b80-c328-11e8-9b74-6abad194838f.png)

**Comment by Fousicek** [comment]
Does anyone know if Magic bees are maintend ? Or if i am just inpattien ?

**Comment by Fousicek** [comment]
Please fix the problem so we can have the bees  please please.

**Comment by Fousicek** [comment]
hmm any news about update ?

**Comment by Draskh** [comment]
Does any have a CraftTweaker script for this issue?

**Comment by Fousicek** [comment]
i dont think this can be fixed with CraftTweaker scrip. Unless i missed part where you can change the output  of the bees products.

**Comment by Draskh** [comment]
Indeed, I was not able to find a solution by script.

**Comment by Fousicek** [comment]
Can we get like at least a word that this mod is still supported ? It is long time now.

**Comment by MoonMoonShark** [comment]
hmmm... a year and a half with not even a beep. was really hoping to use these three for my AE2 build. :( the More Bees mod produces certus powder, but that doesn't help make more fluix, since you can't grow fluix from pure certus.
