### ISSUE TITLE
Hives doesnt give any bees[possible crash]

### ISSUE THREAD

**Issue by darkmtbg2** [ForestryMC/MagicBees#7]
Trying to harvest the hives doesnt give any bees magic bees Version 3.0.2 on 1.10.2 and sometimes crashes the client
and theres eleccore{1.7.421} [ElecCore] (ElecCore-1.10.2-1.7.421.jar) 

Description: Ticking player
This happens when i do it in single player on a multiplayer server the server stays online but prints the same line.

java.lang.NoSuchMethodError: forestry.api.apiculture.IHiveDrop.getExtraItems(Lnet/minecraft/world/IBlockAccess;Lnet/minecraft/util/math/BlockPos;I)Lnet/minecraft/util/NonNullList;
	at elec332.core.compat.forestry.bee.IHiveEnum.getDrops(IHiveEnum.java:98)
	at elec332.core.compat.forestry.bee.BlockHive.getDrops(BlockHive.java:129)

As far as i can see the crash text is at line 4053 

![bee](https://cloud.githubusercontent.com/assets/8265526/26727811/5e91e45c-47a8-11e7-8e65-ff3530bab60a.png)
![bee2](https://cloud.githubusercontent.com/assets/8265526/26727810/5e8d17ec-47a8-11e7-804e-a85a224e9947.png)
![bee3](https://cloud.githubusercontent.com/assets/8265526/26727812/5e95e70a-47a8-11e7-9df0-d951181ccc33.png)
![bee4](https://cloud.githubusercontent.com/assets/8265526/26727813/5e964402-47a8-11e7-85a1-f48814b7d536.png)

**Comment by darkmtbg2** [comment]
https://pastebin.com/Czi3EZi9 seems like the txt file doesnt upload. so heres a pastebin

**Comment by Elec332** [comment]
Hmmm, curious why I didnt catch that one whilst testing 1.10.....

**Comment by Elec332** [comment]
Please update to ElecCore 1.7.425
