### ISSUE TITLE
Some bees aren't producing what they are supposed to produce

### ISSUE THREAD

**Issue by BadLucKWyvern** [ForestryMC/MagicBees#71]
I had that problem with some bee, so i can't give all exemples
but the one wich is necessary for me, is that Blizzy bees aren't producing Blizz (Thermal expension ressource)
Im using gendustry's hives, x8 Production upgrade x1 automation upgrade x4 life lenght downgrade
Blizz chances are at 9% and frozen comb at 10%. After few minutes my 2 hive have produced around 50 combs and 0 Blizz

**Comment by Fousicek** [comment]
You need to place winter emulation into the industrial apiary. New mechanics require bees to be in their prefered type of biom to produce the secondary outputs.

**Comment by BadLucKWyvern** [comment]
Even if i gave the best genome to them allowing them to have +3 hot and +3
cold ? >.<
Thanks for the reply :3

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Elec332** [comment]
Yep, the bees only produce their speciality if they are "jubilant", which requires them to be in their preferred biome
