### ISSUE TITLE
Thaumcraft adds Copper, Tin, Silver, and Lead Nuggets, but not Ingots. Causes various issues

### ISSUE THREAD

**Issue by PokeMaserJ** [ForestryMC/MagicBees#73]
Magic Bees adds bees for various metal resources when there are no Ingots, but there are Nuggets causing various issues. 

reported to Thaumcraft, but Azanor said he can't do anything about it w/o breaking peoples saves

Thaumcraft Beta 24
MagicBees-1.12.2-3.1.10

**Comment by Nedelosk** [comment]
What are these "various issues"?

**Comment by PokeMaserJ** [comment]
With just those mods, there are bees that produce those resources, but no way to get them, since Magic Bees normally needs the resource block under the bee housing in order to mutate. And that is an issue since for example the Gold producing bee needs the Lead producing bee to mutate; or the Silver producing bee is require to get the Emerald producing bee
