### ISSUE TITLE
Aluminum bees require an "aluminium" block

### ISSUE THREAD

**Issue by belathus** [ForestryMC/MagicBees#74]
Unfortunately, none of the aluminum blocks in my current modpack are registered as "blockAluminium," making it impossible to breed aluminum bees.

Just to be clear, I'm referring to the British spelling vs. the American spelling of Aluminum.

I'm using CraftTweaker to add "blockAluminium" to all items in the "blockAluminum" oredict entry.

**Comment by ktole1999** [comment]
i think they are 2 separate minerals. might want to confirm before you start changing recipes.
