### ISSUE TITLE
Deep hive is very generous in redstone blocks

### ISSUE THREAD

**Issue by LemADEC** [ForestryMC/MagicBees#78]
As of forestry_1.12.2-5.8.2.374 + MagicBees-1.12.2-3.1.10, I can see ~30 redstone blocks around each deep hive.
Also, you can find 2 Deep hives within 4 blocks of each others, in the same chunk, along with almost a stack of redstone blocks.
![image](https://user-images.githubusercontent.com/4776032/49483131-50a76100-f832-11e8-8248-2a7683231e28.png)

In comparison, the Infernal hive is surrounded by ~10 glowstone blocks.

I suggest to seriously reduce the redstone blocks surrounding Deep hives, and preferably add an option so we can adjust it.

**Comment by Freebi85** [comment]
I agree with that. That is too exaggerated in momemnt.

**Comment by Elec332** [comment]
The block spawn rate has been ~halved and I lowered the Deep Hive generation chance by 24% aswell.
