### ISSUE TITLE
magicbees-1.7.10-2.4.4.jar seems to have a coding issue

### ISSUE THREAD

**Issue by ILove-Cartilage** [ForestryMC/MagicBees#81]
I'm using technic launcher and the modpack is 1.7.10 but whenever i launch it up it just crashes. I was gonna play on my friends server so deleting it isnt a fix for me. Can you please fix that. Thank you in advance

**Comment by Elec332** [comment]
Without a crashlog I can't help you

**Comment by Elec332** [comment]
Please open a new issue if you have any problems. Remember to post the crashlog aswell, as we cannot help you without one.
