### ISSUE TITLE
Various Bee issues

### ISSUE THREAD

**Issue by PokeMaserJ** [ForestryMC/MagicBees#82]
Porcine can't be mutated, Extreme Hills is now Cold Temp; both the bees needed to breed it, require normal temp and no tolerance.

Big Bad HAS to be bred during a Full Moon, description says other wise

Smouldering can't be worked with, Requires Hellish Temp, and Normal Humidity. Nether is the only 	place that has Hellish Temp, but it has Arid Humitity

Magic Bees 3.1.0

**Comment by Elec332** [comment]
Point 2 and 3 have been fixed in a previous commit. (I know im a year late, I apologise)
Point 1 is fair, as there are only 2 biomes that are normal temp and classify as mountains (mutated roofed forest and mutated birch forest). I will add "hills" to the valid biomes list
