### ISSUE TITLE
[1.11.2] Magnet Crashes

### ISSUE THREAD

**Issue by TheLimePixel** [ForestryMC/MagicBees#9]
When a player has the magnet in their inventory, they continuously crash unless it's manually removed from their inventory from the server files. There's nothing in the logs though.

**Comment by Elec332** [comment]
If they crash, there must be a crashlog or something. Please upload a crash report

**Comment by Xiaminou** [comment]
Whenever you are using the magnet (item on the floor being pulled by the magnet) it will terminate the connection to the server, and you're then locked out of the server until you find a way to remove the magnet.

Here are my client's logs: [latest.txt](https://github.com/ForestryMC/MagicBees/files/1124543/latest.txt)

**Comment by darkmtbg2** [comment]
Most of the crashes i see now (On the latest commit is just Server side with didicated servers)
